import 'dart:async';

import 'package:dartantic_interface/dartantic_interface.dart';
import 'package:http/http.dart' as http;
import 'package:logging/logging.dart';
import 'package:openai_dart/openai_dart.dart' as openai;

import '../../retry_http_client.dart';
import '../../shared/openai_utils.dart';
import 'openai_responses_chat_options.dart';
import 'openai_responses_event_mapper.dart';
import 'openai_responses_invocation_builder.dart';
import 'openai_responses_server_side_tool_mapper.dart';

/// Chat model backed by the OpenAI Responses API.
class OpenAIResponsesChatModel
    extends ChatModel<OpenAIResponsesChatModelOptions> {
  /// Creates a new OpenAI Responses chat model instance.
  OpenAIResponsesChatModel({
    required super.name,
    required super.defaultOptions,
    super.tools,
    super.temperature,
    this.baseUrl,
    this.apiKey,
    http.Client? httpClient,
    Map<String, String>? headers,
  }) : _client = openai.OpenAIClient(
         config: openai.OpenAIConfig(
           authProvider: apiKey != null ? openai.ApiKeyProvider(apiKey) : null,
           baseUrl: baseUrl?.toString() ?? 'https://api.openai.com/v1',
           defaultHeaders: headers ?? const {},
           retryPolicy: const openai.RetryPolicy(maxRetries: 0),
         ),
         httpClient: RetryHttpClient(inner: httpClient ?? http.Client()),
       );

  static final Logger _logger = Logger(
    'dartantic.chat.models.openai_responses',
  );

  final openai.OpenAIClient _client;

  /// Base URL override for the OpenAI API.
  final Uri? baseUrl;

  /// API key used for authentication.
  final String? apiKey;

  List<openai.ResponseTool> _buildFunctionTools() {
    final registeredTools = tools;
    if (registeredTools == null || registeredTools.isEmpty) {
      return const [];
    }

    final mapped = registeredTools
        .map(
          (tool) => openai.FunctionTool(
            name: tool.name,
            description: tool.description,
            // OpenAI Responses API requires 'properties' field on object
            // schemas, even if empty
            parameters: OpenAIUtils.prepareSchemaForOpenAI(
              Map<String, dynamic>.from(tool.inputSchema.value),
            ),
          ),
        )
        .toList(growable: false);
    return mapped;
  }

  @override
  Stream<ChatResult<ChatMessage>> sendStream(
    List<ChatMessage> messages, {
    OpenAIResponsesChatModelOptions? options,
    Schema? outputSchema,
  }) async* {
    final invocation = _buildInvocation(messages, options, outputSchema);
    _validateInvocation(invocation);
    final rawStream = _sendRawRequest(invocation);
    final mapper = _createMapper(invocation);
    yield* _consumeResponseStream(rawStream, mapper);
  }

  @override
  void dispose() => _client.close();

  /// Downloads a file from a code interpreter container.
  ///
  /// Files are generated by server-side code interpreter tool execution
  /// and need to be retrieved separately after the response completes.
  Future<ContainerFileData> downloadContainerFile(
    String containerId,
    String fileId,
  ) async {
    _logger.fine('Downloading container file: $fileId from $containerId');

    // Download content directly. The ContainerFile metadata retrieve call is
    // skipped because openai_dart 1.1.0 has a bug where ContainerFile.fromJson
    // crashes on null `bytes` field. The filename is supplied by the caller via
    // the ContainerFileCitation annotation instead.
    final bytes = await _client.containers.files.retrieveContent(
      containerId,
      fileId,
    );

    return ContainerFileData(bytes: bytes);
  }

  List<openai.ResponseTool> _buildAllTools(
    OpenAIServerSideToolContext context,
  ) => [
    ..._buildFunctionTools(),
    ...OpenAIResponsesServerSideToolMapper.buildServerSideTools(
      serverSideTools: context.enabledTools,
      fileSearchConfig: context.fileSearchConfig,
      webSearchConfig: context.webSearchConfig,
      codeInterpreterConfig: context.codeInterpreterConfig,
      imageGenerationConfig: context.imageGenerationConfig,
    ),
  ];

  OpenAIResponsesInvocation _buildInvocation(
    List<ChatMessage> messages,
    OpenAIResponsesChatModelOptions? options,
    Schema? outputSchema,
  ) => OpenAIResponsesInvocationBuilder(
    messages: messages,
    options: options,
    defaultOptions: defaultOptions,
    outputSchema: outputSchema,
  ).build();

  void _validateInvocation(OpenAIResponsesInvocation invocation) {
    if ((invocation.serverSide.codeInterpreterConfig?.shouldReuseContainer ??
            false) &&
        !invocation.store) {
      _logger.warning(
        'Code interpreter container reuse requested but store=false; '
        'previous_response_id will not be persisted.',
      );
    }
  }

  Stream<Map<String, dynamic>> _sendRawRequest(
    OpenAIResponsesInvocation invocation,
  ) {
    final allTools = _buildAllTools(invocation.serverSide);
    final textFormat = invocation.parameters.textFormat;

    final requestBody = openai.CreateResponseRequest(
      model: name,
      input: invocation.history.input ?? const openai.ResponseInputText(''),
      instructions: invocation.history.instructions,
      previousResponseId: invocation.history.previousResponseId,
      store: invocation.store,
      temperature: invocation.parameters.temperature ?? temperature,
      topP: invocation.parameters.topP,
      maxOutputTokens: invocation.parameters.maxOutputTokens,
      reasoning: invocation.parameters.reasoning,
      text: textFormat != null ? openai.TextConfig(format: textFormat) : null,
      toolChoice: null,
      tools: allTools.isEmpty ? null : allTools,
      parallelToolCalls: invocation.parameters.parallelToolCalls,
      metadata: invocation.parameters.metadata,
      include: invocation.parameters.include
          ?.map(openai.Include.fromJson)
          .toList(),
      truncation: invocation.parameters.truncation,
    ).toJson();
    requestBody['stream'] = true;

    // Use streamSseEvents directly to access raw JSON maps, which allows:
    // 1. Extracting container_id from code_interpreter_call items (the SDK's
    //    typed CodeInterpreterCallOutputItem drops this field during parsing)
    // 2. Skipping unknown event types like keepalive (SDK 1.1.0 bug)
    return _client.responses.streamSseEvents(
      endpoint: '/responses',
      body: requestBody,
    );
  }

  OpenAIResponsesEventMapper _createMapper(
    OpenAIResponsesInvocation invocation,
  ) => OpenAIResponsesEventMapper(
    storeSession: invocation.store,
    downloadContainerFile: downloadContainerFile,
  );

  Stream<ChatResult<ChatMessage>> _consumeResponseStream(
    Stream<Map<String, dynamic>> rawStream,
    OpenAIResponsesEventMapper mapper,
  ) async* {
    try {
      await for (final json in rawStream) {
        final type = json['type'] as String?;

        // Extract container_id from code_interpreter_call items in
        // response.output_item.done events (not parsed by SDK typed classes).
        if (type == 'response.output_item.done') {
          final item = json['item'] as Map<String, dynamic>?;
          if (item != null && item['type'] == 'code_interpreter_call') {
            final containerId = item['container_id'] as String?;
            if (containerId != null) {
              mapper.containerId = containerId;
            }
          }
        }

        // 'keepalive' is a connection-maintenance event from the OpenAI API
        // during long-running operations. Not a model event — skip it.
        if (type == 'keepalive') continue;

        final event = openai.ResponseStreamEvent.fromJson(json);

        _logger.fine('Received event: ${event.runtimeType}');
        yield* mapper.handle(event);
      }
    } on Object catch (error, stackTrace) {
      _logger.severe(
        'OpenAI Responses stream error: $error',
        error,
        stackTrace,
      );
      rethrow;
    }
  }
}
